import '../models/booking_model.dart';
import '../models/trainer_model.dart';
import '../models/user_model.dart';
import '../models/payment_model.dart';

class MockDataService {
  static final User currentUser = User(
    id: 'user_001',
    firstName: 'Александр',
    lastName: 'Морозов',
    email: 'alex.morozov@email.com',
    phone: '+7 (999) 123-45-67',
    birthDate: DateTime(1990, 5, 15),
    photoUrl: null,
    preferences: ['теннис', 'силовые тренировки', 'йога'],
    membership: Membership(
      id: 'mem_001',
      type: 'All-inclusive',
      startDate: DateTime(2025, 9, 1),
      endDate: DateTime(2025, 9, 30),
      remainingVisits: 0, // unlimited
      price: 25000,
      includedServices: ['тренажерный зал', 'групповые занятия', 'теннис'],
      autoRenew: true,
    ),
    balance: 1500,
    lockers: [
      lockers[3], // Добавляем арендованный шкафчик для тестирования
    ],
  );

  static final List<Trainer> trainers = [
    Trainer(
      id: 'trainer_001',
      firstName: 'Мария',
      lastName: 'Иванова',
      specialty: 'Теннис, Кардио-тренировки',
      bio: 'Профессиональный тренер с 10-летним опытом. Специализация: теннис для начинающих и продвинутых игроков, кардио-тренировки.',
      rating: 4.8,
      totalReviews: 124,
      certifications: ['ITF Level 2', 'Fitness Instructor Certification'],
      photoUrl: null,
      availableSports: ['теннис', 'кардио', 'функциональный тренинг'],
      hourlyRates: {'теннис': 2000, 'персональная тренировка': 1500},
    ),
    Trainer(
      id: 'trainer_002',
      firstName: 'Дмитрий',
      lastName: 'Петров',
      specialty: 'Силовые тренировки, Бодибилдинг',
      bio: 'Мастер спорта по пауэрлифтингу. Специализируется на силовых тренировках и построении мышечной массы.',
      rating: 4.9,
      totalReviews: 89,
      certifications: ['Master Trainer', 'Nutrition Specialist'],
      photoUrl: null,
      availableSports: ['силовые тренировки', 'бодибилдинг', 'кроссфит'],
      hourlyRates: {'персональная тренировка': 1800},
    ),
    Trainer(
      id: 'trainer_003',
      firstName: 'Елена',
      lastName: 'Сидорова',
      specialty: 'Йога, Пилатес, Стретчинг',
      bio: 'Сертифицированный инструктор по йоге и пилатесу. Помогает достичь гармонии тела и разума.',
      rating: 4.7,
      totalReviews: 67,
      certifications: ['Yoga Alliance 500h', 'Pilates Instructor'],
      photoUrl: null,
      availableSports: ['йога', 'пилатес', 'стретчинг'],
      hourlyRates: {'групповое занятие': 800, 'персональное': 1200},
    ),
  ];

  static final List<TennisCourt> tennisCourts = [
    TennisCourt(
      id: 'court_001',
      number: 'Корт 1',
      surfaceType: 'Хард',
      isIndoor: true,
      isAvailable: true,
      pricePerHour: 1500,
    ),
    TennisCourt(
      id: 'court_002',
      number: 'Корт 2',
      surfaceType: 'Грунт',
      isIndoor: false,
      isAvailable: true,
      pricePerHour: 1200,
    ),
    TennisCourt(
      id: 'court_003',
      number: 'Корт 3',
      surfaceType: 'Хард',
      isIndoor: true,
      isAvailable: false,
      pricePerHour: 1500,
    ),
  ];

  static final List<GroupClass> groupClasses = [
    // Занятия на сегодня (17 сентября)
    GroupClass(
      id: 'class_001',
      name: 'Утренняя йога',
      description: 'Расслабляющая утренняя практика для пробуждения тела и разума',
      type: 'Йога',
      level: 'Начинающий',
      trainerId: 'trainer_003',
      trainerName: 'Елена Сидорова',
      maxParticipants: 15,
      currentParticipants: 12,
      startTime: DateTime(2025, 9, 17, 8, 0),
      endTime: DateTime(2025, 9, 17, 9, 0),
      location: 'Зал 2',
      price: 500,
    ),
    GroupClass(
      id: 'class_002',
      name: 'HIIT тренировка',
      description: 'Высокоинтенсивная интервальная тренировка для сжигания жира',
      type: 'Кардио',
      level: 'Продвинутый',
      trainerId: 'trainer_001',
      trainerName: 'Мария Иванова',
      maxParticipants: 20,
      currentParticipants: 18,
      startTime: DateTime(2025, 9, 17, 18, 0),
      endTime: DateTime(2025, 9, 17, 19, 0),
      location: 'Зал 1',
      price: 600,
    ),
    GroupClass(
      id: 'class_003',
      name: 'Массаж расслабляющий',
      description: 'Расслабляющий массаж всего тела для снятия напряжения',
      type: 'Массаж',
      level: 'Все уровни',
      trainerId: 'trainer_massage',
      trainerName: 'Анна Ковалева',
      maxParticipants: 1,
      currentParticipants: 0,
      startTime: DateTime(2025, 9, 17, 19, 30),
      endTime: DateTime(2025, 9, 17, 20, 30),
      location: 'Массажный кабинет',
      price: 2500,
    ),

    // Занятия на завтра (18 сентября)
    GroupClass(
      id: 'class_004',
      name: 'Теннисный корт - утренняя сессия',
      description: 'Аренда теннисного корта для индивидуальной тренировки',
      type: 'Теннис',
      level: 'Все уровни',
      trainerId: '',
      trainerName: 'Самостоятельно',
      maxParticipants: 4,
      currentParticipants: 1,
      startTime: DateTime(2025, 9, 18, 9, 0),
      endTime: DateTime(2025, 9, 18, 10, 0),
      location: 'Корт 2',
      price: 1200,
    ),
    GroupClass(
      id: 'class_005',
      name: 'Пилатес',
      description: 'Укрепление мышечного корсета и улучшение осанки',
      type: 'Пилатес',
      level: 'Средний',
      trainerId: 'trainer_003',
      trainerName: 'Елена Сидорова',
      maxParticipants: 12,
      currentParticipants: 8,
      startTime: DateTime(2025, 9, 18, 17, 0),
      endTime: DateTime(2025, 9, 18, 18, 0),
      location: 'Зал 3',
      price: 550,
    ),

    // Занятия на послезавтра (19 сентября)
    GroupClass(
      id: 'class_006',
      name: 'Теннис с тренером',
      description: 'Индивидуальное занятие по тенnis с профессиональным тренером',
      type: 'Теннис',
      level: 'Продвинутый',
      trainerId: 'trainer_001',
      trainerName: 'Мария Иванова',
      maxParticipants: 1,
      currentParticipants: 1,
      startTime: DateTime(2025, 9, 19, 16, 0),
      endTime: DateTime(2025, 9, 19, 17, 0),
      location: 'Корт 1',
      price: 2000,
    ),
    GroupClass(
      id: 'class_007',
      name: 'Функциональный тренинг',
      description: 'Тренировка для развития силы, выносливости и координации',
      type: 'Функциональный',
      level: 'Средний',
      trainerId: 'trainer_002',
      trainerName: 'Дмитрий Петров',
      maxParticipants: 15,
      currentParticipants: 10,
      startTime: DateTime(2025, 9, 19, 19, 0),
      endTime: DateTime(2025, 9, 19, 20, 0),
      location: 'Зал 1',
      price: 650,
    ),
  ];

  static final List<Booking> userBookings = [
    // Бронирования на сегодня (17 сентября)
    Booking(
      id: 'booking_001',
      userId: 'user_001',
      type: BookingType.groupClass,
      startTime: DateTime(2025, 9, 17, 18, 0),
      endTime: DateTime(2025, 9, 17, 19, 0),
      title: 'HIIT тренировка',
      description: 'С Марией Ивановой',
      status: BookingStatus.confirmed,
      price: 600,
      trainerId: 'trainer_001',
      className: 'HIIT тренировка',
      createdAt: DateTime(2025, 9, 12),
    ),
    Booking(
      id: 'booking_002',
      userId: 'user_001',
      type: BookingType.groupClass,
      startTime: DateTime(2025, 9, 17, 19, 30),
      endTime: DateTime(2025, 9, 17, 20, 30),
      title: 'Массаж расслабляющий',
      description: 'С Анной Ковалевой',
      status: BookingStatus.confirmed,
      price: 2500,
      trainerId: 'trainer_massage',
      className: 'Массаж расслабляющий',
      createdAt: DateTime(2025, 9, 13),
    ),

    // Бронирования на завтра (18 сентября)
    Booking(
      id: 'booking_003',
      userId: 'user_001',
      type: BookingType.tennisCourt,
      startTime: DateTime(2025, 9, 18, 9, 0),
      endTime: DateTime(2025, 9, 18, 10, 0),
      title: 'Теннисный корт',
      description: 'Корт 2 - Грунт',
      status: BookingStatus.confirmed,
      price: 1200,
      courtNumber: 'Корт 2',
      createdAt: DateTime(2025, 9, 10),
    ),
    Booking(
      id: 'booking_004',
      userId: 'user_001',
      type: BookingType.groupClass,
      startTime: DateTime(2025, 9, 18, 17, 0),
      endTime: DateTime(2025, 9, 18, 18, 0),
      title: 'Пилатес',
      description: 'С Еленой Сидоровой',
      status: BookingStatus.confirmed,
      price: 550,
      trainerId: 'trainer_003',
      className: 'Пилатес',
      createdAt: DateTime(2025, 9, 14),
    ),

    // Бронирования на послезавтра (19 сентября)
    Booking(
      id: 'booking_005',
      userId: 'user_001',
      type: BookingType.personalTraining,
      startTime: DateTime(2025, 9, 19, 16, 0),
      endTime: DateTime(2025, 9, 19, 17, 0),
      title: 'Теннис с тренером',
      description: 'С Марией Ивановой',
      status: BookingStatus.confirmed,
      price: 2000,
      trainerId: 'trainer_001',
      className: 'Теннис с тренером',
      createdAt: DateTime(2025, 9, 14),
    ),
    Booking(
      id: 'booking_006',
      userId: 'user_001',
      type: BookingType.groupClass,
      startTime: DateTime(2025, 9, 19, 19, 0),
      endTime: DateTime(2025, 9, 19, 20, 0),
      title: 'Функциональный тренинг',
      description: 'С Дмитрием Петровым',
      status: BookingStatus.confirmed,
      price: 650,
      trainerId: 'trainer_002',
      className: 'Функциональный тренинг',
      createdAt: DateTime(2025, 9, 15),
    ),

    // Бронирования на 20 сентября
    Booking(
      id: 'booking_007',
      userId: 'user_001',
      type: BookingType.groupClass,
      startTime: DateTime(2025, 9, 20, 12, 0),
      endTime: DateTime(2025, 9, 20, 13, 0),
      title: 'Стретчинг',
      description: 'С Еленой Сидоровой',
      status: BookingStatus.confirmed,
      price: 500,
      trainerId: 'trainer_003',
      className: 'Стретчинг',
      createdAt: DateTime(2025, 9, 16),
    ),

    // Бронирования на 21 сентября
    Booking(
      id: 'booking_008',
      userId: 'user_001',
      type: BookingType.groupClass,
      startTime: DateTime(2025, 9, 21, 17, 0),
      endTime: DateTime(2025, 9, 21, 18, 0),
      title: 'Кроссфит',
      description: 'С Дмитрием Петровым',
      status: BookingStatus.confirmed,
      price: 700,
      trainerId: 'trainer_002',
      className: 'Кроссфит',
      createdAt: DateTime(2025, 9, 16),
    ),
    Booking(
      id: 'booking_009',
      userId: 'user_001',
      type: BookingType.tennisCourt,
      startTime: DateTime(2025, 9, 21, 19, 0),
      endTime: DateTime(2025, 9, 21, 20, 30),
      title: 'Теннисный корт',
      description: 'Корт 1 - Хард',
      status: BookingStatus.confirmed,
      price: 2250,
      courtNumber: 'Корт 1',
      createdAt: DateTime(2025, 9, 16),
    ),

    // Бронирования на 22 сентября
    Booking(
      id: 'booking_010',
      userId: 'user_001',
      type: BookingType.personalTraining,
      startTime: DateTime(2025, 9, 22, 10, 0),
      endTime: DateTime(2025, 9, 22, 11, 0),
      title: 'Силовая тренировка',
      description: 'С Дмитрием Петровым',
      status: BookingStatus.confirmed,
      price: 1800,
      trainerId: 'trainer_002',
      className: 'Силовая тренировка',
      createdAt: DateTime(2025, 9, 17),
    ),
  ];


  static final List<MembershipType> membershipTypes = [
    MembershipType(
      id: 'type_001',
      name: 'Тренажерный зал',
      description: 'Доступ только в тренажерный зал',
      price: 8000,
      durationDays: 30,
      maxVisits: 12,
      includesGym: true,
    ),
    MembershipType(
      id: 'type_002',
      name: 'Групповые занятия',
      description: 'Неограниченный доступ к групповым занятиям',
      price: 12000,
      durationDays: 30,
      includesGroupClasses: true,
    ),
    MembershipType(
      id: 'type_003',
      name: 'All-inclusive',
      description: 'Полный доступ ко всем услугам клуба',
      price: 25000,
      durationDays: 30,
      includesTennis: true,
      includesGym: true,
      includesGroupClasses: true,
      tennisCourtDiscount: 0.2,
      personalTrainingDiscount: 0.15,
    ),
    MembershipType(
      id: 'type_004',
      name: 'Теннис',
      description: 'Доступ к теннисным кортам + 4 часа в месяц',
      price: 15000,
      durationDays: 30,
      includesTennis: true,
      maxVisits: 4,
    ),
  ];

  static final List<Locker> lockers = [
    Locker(
      id: 'locker_001',
      number: 'A-101',
      size: 'Стандартный',
      isAvailable: true,
      pricePerDay: 100,
    ),
    Locker(
      id: 'locker_002',
      number: 'A-102',
      size: 'Стандартный',
      isAvailable: true,
      pricePerDay: 100,
    ),
    Locker(
      id: 'locker_003',
      number: 'A-103',
      size: 'Большой',
      isAvailable: true,
      pricePerDay: 150,
    ),
    Locker(
      id: 'locker_004',
      number: 'A-104',
      size: 'Стандартный',
      isAvailable: false,
      pricePerDay: 100,
      rentalEndDate: DateTime(2025, 9, 20),
    ),
    Locker(
      id: 'locker_005',
      number: 'B-201',
      size: 'Большой',
      isAvailable: true,
      pricePerDay: 150,
    ),
  ];
}