import '../../models/chat_model.dart';

final List<ChatMessage> mockChatMessages = [
  ChatMessage(
    id: 'msg_001',
    chatId: 'chat_001',
    type: MessageType.system,
    sender: MessageSender.system,
    content: 'Чат с администратором открыт',
    timestamp: DateTime(2025, 9, 18, 10, 0),
    isRead: true,
  ),
  ChatMessage(
    id: 'msg_002',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.admin,
    content: 'Добрый день! Чем могу помочь?',
    timestamp: DateTime(2025, 9, 18, 10, 1),
    isRead: true,
    senderName: 'Администратор',
    senderAvatar: null,
  ),
  ChatMessage(
    id: 'msg_003',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.user,
    content: 'Здравствуйте! Хочу уточнить по поводу завтрашней тренировки',
    timestamp: DateTime(2025, 9, 18, 10, 5),
    isRead: true,
  ),
  ChatMessage(
    id: 'msg_004',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.admin,
    content: 'Конечно! Что именно вас интересует?',
    timestamp: DateTime(2025, 9, 18, 10, 7),
    isRead: true,
    senderName: 'Администратор',
    senderAvatar: null,
  ),
  ChatMessage(
    id: 'msg_005',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.user,
    content: 'Можно ли перенести тренировку на час позже?',
    timestamp: DateTime(2025, 9, 18, 10, 10),
    isRead: true,
  ),
  ChatMessage(
    id: 'msg_006',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.admin,
    content: 'Да, проверю доступность. Одну минуту...',
    timestamp: DateTime(2025, 9, 18, 10, 12),
    isRead: true,
    senderName: 'Администратор',
    senderAvatar: null,
  ),
  ChatMessage(
    id: 'msg_007',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.admin,
    content: 'Да, время свободно! Перенес вашу тренировку на 11:00',
    timestamp: DateTime(2025, 9, 18, 10, 15),
    isRead: false,
    senderName: 'Администратор',
    senderAvatar: null,
  ),
];

final Chat mockChat = Chat(
  id: 'chat_001',
  userId: 'user_001',
  adminId: 'admin_001',
  adminName: 'Администратор фитнес-центра',
  adminAvatar: null,
  createdAt: DateTime(2025, 9, 18, 10, 0),
  updatedAt: DateTime(2025, 9, 18, 10, 15),
  messages: mockChatMessages,
  isActive: true,
  unreadCount: 1,
);