import '../../models/chat_model.dart';

final List<ChatMessage> mockChatMessages = [
  ChatMessage(
    id: 'msg_001',
    chatId: 'chat_001',
    type: MessageType.system,
    sender: MessageSender.system,
    content: 'Чат с администратором открыт',
    timestamp: DateTime(2025, 9, 22, 10, 0),
    isRead: true,
  ),
  ChatMessage(
    id: 'msg_002',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.admin,
    content: 'Добрый день! Чем могу помочь?',
    timestamp: DateTime(2025, 9, 22, 10, 1),
    isRead: true,
    senderName: 'Администратор',
    senderAvatar: null,
  ),
  ChatMessage(
    id: 'msg_003',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.user,
    content: 'Здравствуйте! Хочу уточнить по поводу завтрашней тренировки',
    timestamp: DateTime(2025, 9, 22, 10, 5),
    isRead: true,
  ),
  ChatMessage(
    id: 'msg_004',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.admin,
    content: 'Конечно! Что именно вас интересует?',
    timestamp: DateTime(2025, 9, 22, 10, 7),
    isRead: true,
    senderName: 'Администратор',
    senderAvatar: null,
  ),
  ChatMessage(
    id: 'msg_005',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.user,
    content: 'Можно ли перенести тренировку на час позже?',
    timestamp: DateTime(2025, 9, 22, 10, 10),
    isRead: true,
  ),
  ChatMessage(
    id: 'msg_006',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.admin,
    content: 'Да, проверю доступность. Одну минуту...',
    timestamp: DateTime(2025, 9, 22, 10, 12),
    isRead: true,
    senderName: 'Администратор',
    senderAvatar: null,
  ),
  ChatMessage(
    id: 'msg_007',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.admin,
    content: 'Да, время свободно! Перенес вашу тренировку на 11:00',
    timestamp: DateTime(2025, 9, 22, 10, 15),
    isRead: false,
    senderName: 'Администратор',
    senderAvatar: null,
  ),
  ChatMessage(
    id: 'msg_008',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.user,
    content: 'Спасибо большое! А можно ли также забронировать шкафчик на это время?',
    timestamp: DateTime(2025, 9, 22, 10, 18),
    isRead: true,
  ),
  ChatMessage(
    id: 'msg_009',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.admin,
    content: 'Конечно! Шкафчик A-102 свободен. Забронировал для вас.',
    timestamp: DateTime(2025, 9, 22, 10, 20),
    isRead: false,
    senderName: 'Администратор',
    senderAvatar: null,
  ),
  ChatMessage(
    id: 'msg_010',
    chatId: 'chat_001',
    type: MessageType.system,
    sender: MessageSender.system,
    content: 'Шкафчик A-102 успешно забронирован',
    timestamp: DateTime(2025, 9, 22, 10, 21),
    isRead: false,
  ),
  ChatMessage(
    id: 'msg_011',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.user,
    content: 'Отлично! Еще вопрос: есть ли скидки на массаж для членов клуба?',
    timestamp: DateTime(2025, 9, 22, 10, 25),
    isRead: true,
  ),
  ChatMessage(
    id: 'msg_012',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.admin,
    content: 'Да, для владельцев абонемента All-inclusive скидка 15% на все массажные услуги.',
    timestamp: DateTime(2025, 9, 22, 10, 28),
    isRead: false,
    senderName: 'Администратор',
    senderAvatar: null,
  ),
  ChatMessage(
    id: 'msg_013',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.user,
    content: 'Отлично, спасибо за информацию!',
    timestamp: DateTime(2025, 9, 22, 10, 30),
    isRead: true,
  ),
  ChatMessage(
    id: 'msg_014',
    chatId: 'chat_001',
    type: MessageType.text,
    sender: MessageSender.admin,
    content: 'Всегда рады помочь! Если возникнут еще вопросы - обращайтесь.',
    timestamp: DateTime(2025, 9, 22, 10, 32),
    isRead: false,
    senderName: 'Администратор',
    senderAvatar: null,
  ),
];

final Chat mockChat = Chat(
  id: 'chat_001',
  userId: 'user_001',
  adminId: 'admin_001',
  adminName: 'Администратор фитнес-центра',
  adminAvatar: null,
  createdAt: DateTime(2025, 9, 22, 10, 0),
  updatedAt: DateTime(2025, 9, 22, 10, 32),
  messages: mockChatMessages,
  isActive: true,
  unreadCount: 5,
);