import '../../models/user_model.dart';

final List<User> clients = [
  User(
    id: 'client_001',
    firstName: 'Иван',
    lastName: 'Петров',
    email: 'ivan.petrov@email.com',
    phone: '+7 (999) 111-22-33',
    birthDate: DateTime(1985, 3, 12),
    photoUrl: null,
    preferences: ['теннис', 'плавание'],
    membership: Membership(
      id: 'mem_002',
      type: 'Standard',
      startDate: DateTime(2025, 9, 5),
      endDate: DateTime(2025, 10, 4),
      remainingVisits: 12,
      price: 15000,
      includedServices: ['тренажерный зал', 'групповые занятия'],
      autoRenew: true,
    ),
    balance: 1500,
    bankCards: [],
    lockers: [],
    bookings: [],
  ),
  User(
    id: 'client_002',
    firstName: 'Елена',
    lastName: 'Сидорова',
    email: 'elena.sidorova@email.com',
    phone: '+7 (999) 222-33-44',
    birthDate: DateTime(1992, 7, 25),
    photoUrl: null,
    preferences: ['йога', 'пилатес', 'стретчинг'],
    membership: Membership(
      id: 'mem_003',
      type: 'Premium',
      startDate: DateTime(2025, 9, 5),
      endDate: DateTime(2026, 1, 4),
      remainingVisits: 0,
      price: 30000,
      includedServices: ['тренажерный зал', 'групповые занятия', 'бассейн', 'сауна'],
      autoRenew: true,
    ),
    balance: 5000,
    bankCards: [],
    lockers: [],
    bookings: [],
  ),
  User(
    id: 'client_003',
    firstName: 'Дмитрий',
    lastName: 'Кузнецов',
    email: 'dmitry.kuznetsov@email.com',
    phone: '+7 (999) 333-44-55',
    birthDate: DateTime(1988, 11, 5),
    photoUrl: null,
    preferences: ['бокс', 'единоборства', 'функциональный тренинг'],
    membership: Membership(
      id: 'mem_004',
      type: 'All-inclusive',
      startDate: DateTime(2025, 9, 5),
      endDate: DateTime(2025, 10, 4),
      remainingVisits: 0,
      price: 25000,
      includedServices: ['тренажерный зал', 'групповые занятия', 'теннис', 'бассейн'],
      autoRenew: true,
    ),
    balance: 2000,
    bankCards: [],
    lockers: [],
    bookings: [],
  ),
  User(
    id: 'client_004',
    firstName: 'Ольга',
    lastName: 'Иванова',
    email: 'olga.ivanova@email.com',
    phone: '+7 (999) 444-55-66',
    birthDate: DateTime(1995, 2, 18),
    photoUrl: null,
    preferences: ['кардио', 'танцы', 'аэробика'],
    membership: Membership(
      id: 'mem_005',
      type: 'Basic',
      startDate: DateTime(2025, 9, 5),
      endDate: DateTime(2025, 10, 4),
      remainingVisits: 8,
      price: 8000,
      includedServices: ['тренажерный зал'],
      autoRenew: false,
    ),
    balance: 800,
    bankCards: [],
    lockers: [],
    bookings: [],
  ),
  User(
    id: 'client_005',
    firstName: 'Сергей',
    lastName: 'Васильев',
    email: 'sergey.vasiliev@email.com',
    phone: '+7 (999) 555-66-77',
    birthDate: DateTime(1980, 12, 30),
    photoUrl: null,
    preferences: ['силовые тренировки', 'кроссфит', 'пауэрлифтинг'],
    membership: Membership(
      id: 'mem_006',
      type: 'Premium',
      startDate: DateTime(2025, 9, 5),
      endDate: DateTime(2026, 1, 4),
      remainingVisits: 0,
      price: 30000,
      includedServices: ['тренажерный зал', 'групповые занятия', 'бассейн', 'сауна'],
      autoRenew: true,
    ),
    balance: 3500,
    bankCards: [],
    lockers: [],
    bookings: [],
  ),
];