import '../../models/booking_model.dart';

final List<Booking> employeeTrainings = [
  // Тренировки на сегодня (22 сентября) - 3 подтвержденных, 1 ожидает оплаты
  Booking(
    id: 'training_001',
    userId: 'user_002',
    type: BookingType.personalTraining,
    startTime: DateTime(2025, 9, 22, 9, 0),
    endTime: DateTime(2025, 9, 22, 10, 30),
    title: 'Персональная тренировка',
    description: 'Силовая тренировка, работа с техникой',
    status: BookingStatus.confirmed,
    price: 2500,
    trainerId: 'trainer_001',
    className: 'Персональная тренировка',
    createdAt: DateTime(2025, 9, 14),
    clientName: 'Иванов Александр Сергеевич',
  ),
  Booking(
    id: 'training_002',
    userId: 'user_003',
    type: BookingType.groupClass,
    startTime: DateTime(2025, 9, 22, 11, 0),
    endTime: DateTime(2025, 9, 22, 12, 0),
    title: 'Групповое занятие: Йога',
    description: 'Утренняя йога для всех уровней',
    status: BookingStatus.completed,
    price: 600,
    trainerId: 'trainer_001',
    className: 'Йога',
    createdAt: DateTime(2025, 9, 18),
    clientName: 'Группа (12 человек)',
  ),
  Booking(
    id: 'training_003',
    userId: 'user_004',
    type: BookingType.personalTraining,
    startTime: DateTime(2025, 9, 22, 14, 0),
    endTime: DateTime(2025, 9, 22, 15, 30),
    title: 'Персональная тренировка',
    description: 'Кардио и функциональный тренинг',
    status: BookingStatus.confirmed,
    price: 2200,
    trainerId: 'trainer_001',
    className: 'Персональная тренировка',
    createdAt: DateTime(2025, 9, 16),
    clientName: 'Петрова Елена Владимировна',
  ),
  Booking(
    id: 'training_004',
    userId: 'user_005',
    type: BookingType.personalTraining,
    startTime: DateTime(2025, 9, 22, 16, 0),
    endTime: DateTime(2025, 9, 22, 17, 0),
    title: 'Консультация',
    description: 'Составление программы тренировок',
    status: BookingStatus.awaitingPayment,
    price: 1500,
    trainerId: 'trainer_001',
    className: 'Консультация',
    createdAt: DateTime(2025, 9, 20),
    clientName: 'Сидоров Михаил Иванович',
  ),

  // Тренировки на завтра (23 сентября) - 2 подтвержденных, 1 отменена
  Booking(
    id: 'training_005',
    userId: 'user_006',
    type: BookingType.personalTraining,
    startTime: DateTime(2025, 9, 23, 10, 0),
    endTime: DateTime(2025, 9, 23, 11, 30),
    title: 'Персональная тренировка',
    description: 'Работа над выносливостью',
    status: BookingStatus.confirmed,
    price: 2300,
    trainerId: 'trainer_001',
    className: 'Персональная тренировка',
    createdAt: DateTime(2025, 9, 17),
    clientName: 'Кузнецова Ольга Петровна',
  ),
  Booking(
    id: 'training_006',
    userId: 'user_007',
    type: BookingType.groupClass,
    startTime: DateTime(2025, 9, 23, 12, 0),
    endTime: DateTime(2025, 9, 23, 13, 0),
    title: 'Групповое занятие: Фитнес',
    description: 'Силовой тренинг для продвинутых',
    status: BookingStatus.confirmed,
    price: 550,
    trainerId: 'trainer_001',
    className: 'Фитнес',
    createdAt: DateTime(2025, 9, 19),
    clientName: 'Группа (15 человек)',
  ),
  Booking(
    id: 'training_007',
    userId: 'user_008',
    type: BookingType.personalTraining,
    startTime: DateTime(2025, 9, 23, 15, 0),
    endTime: DateTime(2025, 9, 23, 16, 30),
    title: 'Персональная тренировка',
    description: 'Реабилитационная тренировка',
    status: BookingStatus.cancelled,
    price: 2000,
    trainerId: 'trainer_001',
    className: 'Персональная тренировка',
    createdAt: DateTime(2025, 9, 15),
    clientName: 'Николаев Дмитрий Алексеевич',
  ),

  // Тренировки на 24 сентября - 1 подтверждена, 1 ожидает оплаты
  Booking(
    id: 'training_008',
    userId: 'user_009',
    type: BookingType.personalTraining,
    startTime: DateTime(2025, 9, 24, 9, 0),
    endTime: DateTime(2025, 9, 24, 10, 30),
    title: 'Персональная тренировка',
    description: 'Подготовка к соревнованиям',
    status: BookingStatus.confirmed,
    price: 2700,
    trainerId: 'trainer_001',
    className: 'Персональная тренировка',
    createdAt: DateTime(2025, 9, 18),
    clientName: 'Волков Сергей Николаевич',
  ),
  Booking(
    id: 'training_009',
    userId: 'user_010',
    type: BookingType.groupClass,
    startTime: DateTime(2025, 9, 24, 17, 0),
    endTime: DateTime(2025, 9, 24, 18, 0),
    title: 'Групповое занятие: Стретчинг',
    description: 'Растяжка и расслабление',
    status: BookingStatus.awaitingPayment,
    price: 500,
    trainerId: 'trainer_001',
    className: 'Стретчинг',
    createdAt: DateTime(2025, 9, 20),
    clientName: 'Группа (10 человек)',
  ),

  // Тренировки на 25 сентября - 2 подтвержденных
  Booking(
    id: 'training_010',
    userId: 'user_011',
    type: BookingType.personalTraining,
    startTime: DateTime(2025, 9, 25, 11, 0),
    endTime: DateTime(2025, 9, 25, 12, 30),
    title: 'Персональная тренировка',
    description: 'Коррекция осанки',
    status: BookingStatus.confirmed,
    price: 2100,
    trainerId: 'trainer_001',
    className: 'Персональная тренировка',
    createdAt: DateTime(2025, 9, 22),
    clientName: 'Орлова Анна Викторовна',
  ),
  Booking(
    id: 'training_011',
    userId: 'user_012',
    type: BookingType.groupClass,
    startTime: DateTime(2025, 9, 25, 19, 0),
    endTime: DateTime(2025, 9, 25, 20, 0),
    title: 'Групповое занятие: Пилатес',
    description: 'Укрепление мышечного корсета',
    status: BookingStatus.confirmed,
    price: 600,
    trainerId: 'trainer_001',
    className: 'Пилатес',
    createdAt: DateTime(2025, 9, 21),
    clientName: 'Группа (8 человек)',
  ),

  // Тренировки на 26 сентября - 1 подтверждена, 1 отменена
  Booking(
    id: 'training_012',
    userId: 'user_013',
    type: BookingType.personalTraining,
    startTime: DateTime(2025, 9, 26, 14, 0),
    endTime: DateTime(2025, 9, 26, 15, 30),
    title: 'Персональная тренировка',
    description: 'Функциональный тренинг',
    status: BookingStatus.confirmed,
    price: 2400,
    trainerId: 'trainer_001',
    className: 'Персональная тренировка',
    createdAt: DateTime(2025, 9, 23),
    clientName: 'Белов Павел Александрович',
  ),
  Booking(
    id: 'training_013',
    userId: 'user_014',
    type: BookingType.groupClass,
    startTime: DateTime(2025, 9, 26, 16, 0),
    endTime: DateTime(2025, 9, 26, 17, 0),
    title: 'Групповое занятие: Кроссфит',
    description: 'Высокоинтенсивный интервальный тренинг',
    status: BookingStatus.cancelled,
    price: 700,
    trainerId: 'trainer_001',
    className: 'Кроссфит',
    createdAt: DateTime(2025, 9, 24),
    clientName: 'Группа (12 человек)',
  ),

  // Тренировки на 27 сентября - 1 подтверждена, 1 завершена
  Booking(
    id: 'training_014',
    userId: 'user_015',
    type: BookingType.personalTraining,
    startTime: DateTime(2025, 9, 27, 10, 0),
    endTime: DateTime(2025, 9, 27, 11, 30),
    title: 'Персональная тренировка',
    description: 'Снижение веса',
    status: BookingStatus.confirmed,
    price: 2200,
    trainerId: 'trainer_001',
    className: 'Персональная тренировка',
    createdAt: DateTime(2025, 9, 25),
    clientName: 'Громова Ирина Олеговна',
  ),
  Booking(
    id: 'training_015',
    userId: 'user_016',
    type: BookingType.groupClass,
    startTime: DateTime(2025, 9, 27, 18, 0),
    endTime: DateTime(2025, 9, 27, 19, 0),
    title: 'Групповое занятие: Тай-бо',
    description: 'Кардио тренировка с элементами единоборств',
    status: BookingStatus.awaitingPayment,
    price: 650,
    trainerId: 'trainer_001',
    className: 'Тай-бо',
    createdAt: DateTime(2025, 9, 26),
    clientName: 'Группа (14 человек)',
  ),

  // Тренировки на 28 сентября - 1 ожидает оплаты, 1 подтверждена
  Booking(
    id: 'training_016',
    userId: 'user_017',
    type: BookingType.personalTraining,
    startTime: DateTime(2025, 9, 28, 13, 0),
    endTime: DateTime(2025, 9, 28, 14, 30),
    title: 'Персональная тренировка',
    description: 'Набор мышечной массы',
    status: BookingStatus.awaitingPayment,
    price: 2600,
    trainerId: 'trainer_001',
    className: 'Персональная тренировка',
    createdAt: DateTime(2025, 9, 27),
    clientName: 'Титов Максим Сергеевич',
  ),
  Booking(
    id: 'training_017',
    userId: 'user_018',
    type: BookingType.groupClass,
    startTime: DateTime(2025, 9, 28, 20, 0),
    endTime: DateTime(2025, 9, 28, 21, 0),
    title: 'Групповое занятие: Зумба',
    description: 'Танцевальная фитнес-программа',
    status: BookingStatus.confirmed,
    price: 550,
    trainerId: 'trainer_001',
    className: 'Зумба',
    createdAt: DateTime(2025, 9, 28),
    clientName: 'Группа (20 человек)',
  ),

  // Тренировки на 29 сентября - 2 подтвержденных
  Booking(
    id: 'training_018',
    userId: 'user_019',
    type: BookingType.personalTraining,
    startTime: DateTime(2025, 9, 29, 9, 0),
    endTime: DateTime(2025, 9, 29, 10, 30),
    title: 'Персональная тренировка',
    description: 'Подготовка к марафону',
    status: BookingStatus.confirmed,
    price: 2300,
    trainerId: 'trainer_001',
    className: 'Персональная тренировка',
    createdAt: DateTime(2025, 9, 29),
    clientName: 'Федоров Андрей Игоревич',
  ),
  Booking(
    id: 'training_019',
    userId: 'user_020',
    type: BookingType.groupClass,
    startTime: DateTime(2025, 9, 29, 17, 0),
    endTime: DateTime(2025, 9, 29, 18, 0),
    title: 'Групповое занятие: Боди-балет',
    description: 'Силовой тренинг с элементами балета',
    status: BookingStatus.confirmed,
    price: 600,
    trainerId: 'trainer_001',
    className: 'Боди-балет',
    createdAt: DateTime(2025, 9, 30),
    clientName: 'Группа (10 человек)',
  ),
];