import '../../models/trainer_model.dart';

final List<GroupClass> groupClasses = [
  // Занятия на сегодня (18 сентября)
  GroupClass(
    id: 'class_001',
    name: 'Утренняя йога',
    description: 'Расслабляющая утренняя практика для пробуждения тела и разума',
    type: 'Йога',
    level: 'Начинающий',
    trainerId: 'trainer_003',
    trainerName: 'Елена Сидорова',
    maxParticipants: 15,
    currentParticipants: 12,
    startTime: DateTime(2025, 9, 18, 8, 0),
    endTime: DateTime(2025, 9, 18, 9, 0),
    location: 'Зал 2',
    price: 500,
  ),
  GroupClass(
    id: 'class_002',
    name: 'Теннисный корт - утренняя сессия',
    description: 'Аренда теннисного корта для индивидуальной тренировки',
    type: 'Теннис',
    level: 'Все уровни',
    trainerId: '',
    trainerName: 'Самостоятельно',
    maxParticipants: 4,
    currentParticipants: 1,
    startTime: DateTime(2025, 9, 18, 9, 0),
    endTime: DateTime(2025, 9, 18, 10, 0),
    location: 'Корт 2',
    price: 1200,
  ),
  GroupClass(
    id: 'class_003',
    name: 'Пилатес',
    description: 'Укрепление мышечного корсета и улучшение осанки',
    type: 'Пилатес',
    level: 'Средний',
    trainerId: 'trainer_003',
    trainerName: 'Елена Сидорова',
    maxParticipants: 12,
    currentParticipants: 8,
    startTime: DateTime(2025, 9, 18, 17, 0),
    endTime: DateTime(2025, 9, 18, 18, 0),
    location: 'Зал 3',
    price: 550,
  ),
  GroupClass(
    id: 'class_004',
    name: 'HIIT тренировка',
    description: 'Высокоинтенсивная интервальная тренировка для сжигания жира',
    type: 'Кардио',
    level: 'Продвинутый',
    trainerId: 'trainer_001',
    trainerName: 'Мария Иванова',
    maxParticipants: 20,
    currentParticipants: 18,
    startTime: DateTime(2025, 9, 18, 18, 0),
    endTime: DateTime(2025, 9, 18, 19, 0),
    location: 'Зал 1',
    price: 600,
  ),
  GroupClass(
    id: 'class_005',
    name: 'Массаж расслабляющий',
    description: 'Расслабляющий массаж всего тела для снятия напряжения',
    type: 'Массаж',
    level: 'Все уровни',
    trainerId: 'trainer_massage',
    trainerName: 'Анна Ковалева',
    maxParticipants: 1,
    currentParticipants: 0,
    startTime: DateTime(2025, 9, 18, 19, 30),
    endTime: DateTime(2025, 9, 18, 20, 30),
    location: 'Массажный кабинет',
    price: 2500,
  ),

  // Занятия на завтра (19 сентября)
  GroupClass(
    id: 'class_006',
    name: 'Теннис с тренером',
    description: 'Индивидуальное занятие по теннису с профессиональным тренером',
    type: 'Теннис',
    level: 'Продвинутый',
    trainerId: 'trainer_001',
    trainerName: 'Мария Иванова',
    maxParticipants: 1,
    currentParticipants: 1,
    startTime: DateTime(2025, 9, 19, 16, 0),
    endTime: DateTime(2025, 9, 19, 17, 0),
    location: 'Корт 1',
    price: 2000,
  ),
  GroupClass(
    id: 'class_007',
    name: 'Функциональный тренинг',
    description: 'Тренировка для развития силы, выносливости и координации',
    type: 'Функциональный',
    level: 'Средний',
    trainerId: 'trainer_002',
    trainerName: 'Дмитрий Петров',
    maxParticipants: 15,
    currentParticipants: 10,
    startTime: DateTime(2025, 9, 19, 19, 0),
    endTime: DateTime(2025, 9, 19, 20, 0),
    location: 'Зал 1',
    price: 650,
  ),
  GroupClass(
    id: 'class_008',
    name: 'Стретчинг вечерний',
    description: 'Растяжка для улучшения гибкости и расслабления мышц',
    type: 'Стретчинг',
    level: 'Все уровни',
    trainerId: 'trainer_003',
    trainerName: 'Елена Сидорова',
    maxParticipants: 18,
    currentParticipants: 14,
    startTime: DateTime(2025, 9, 19, 20, 30),
    endTime: DateTime(2025, 9, 19, 21, 30),
    location: 'Зал 2',
    price: 450,
  ),

  // Занятия на 20 сентября
  GroupClass(
    id: 'class_009',
    name: 'Стретчинг утренний',
    description: 'Утренняя растяжка для бодрости и гибкости',
    type: 'Стретчинг',
    level: 'Начинающий',
    trainerId: 'trainer_003',
    trainerName: 'Елена Сидорова',
    maxParticipants: 15,
    currentParticipants: 9,
    startTime: DateTime(2025, 9, 20, 9, 0),
    endTime: DateTime(2025, 9, 20, 10, 0),
    location: 'Зал 2',
    price: 500,
  ),
  GroupClass(
    id: 'class_010',
    name: 'Кроссфит',
    description: 'Высокоинтенсивная функциональная тренировка',
    type: 'Кроссфит',
    level: 'Продвинутый',
    trainerId: 'trainer_002',
    trainerName: 'Дмитрий Петров',
    maxParticipants: 16,
    currentParticipants: 12,
    startTime: DateTime(2025, 9, 20, 18, 0),
    endTime: DateTime(2025, 9, 20, 19, 0),
    location: 'Зал 1',
    price: 700,
  ),

  // Занятия на 21 сентября
  GroupClass(
    id: 'class_011',
    name: 'Йога для продвинутых',
    description: 'Продвинутая практика йоги для опытных учеников',
    type: 'Йога',
    level: 'Продвинутый',
    trainerId: 'trainer_003',
    trainerName: 'Елена Сидорова',
    maxParticipants: 12,
    currentParticipants: 8,
    startTime: DateTime(2025, 9, 21, 10, 0),
    endTime: DateTime(2025, 9, 21, 11, 30),
    location: 'Зал 2',
    price: 600,
  ),
  GroupClass(
    id: 'class_012',
    name: 'Силовая тренировка',
    description: 'Тренировка с отягощениями для развития силы',
    type: 'Силовой',
    level: 'Средний',
    trainerId: 'trainer_002',
    trainerName: 'Дмитрий Петров',
    maxParticipants: 20,
    currentParticipants: 15,
    startTime: DateTime(2025, 9, 21, 17, 0),
    endTime: DateTime(2025, 9, 21, 18, 0),
    location: 'Зал 1',
    price: 650,
  ),

  // Занятия на 22 сентября
  GroupClass(
    id: 'class_013',
    name: 'Пилатес реформатор',
    description: 'Занятие на специальном оборудовании для пилатеса',
    type: 'Пилатес',
    level: 'Средний',
    trainerId: 'trainer_003',
    trainerName: 'Елена Сидорова',
    maxParticipants: 8,
    currentParticipants: 6,
    startTime: DateTime(2025, 9, 22, 11, 0),
    endTime: DateTime(2025, 9, 22, 12, 0),
    location: 'Зал 3',
    price: 800,
  ),
  GroupClass(
    id: 'class_014',
    name: 'Кардио-танцы',
    description: 'Танцевальная кардио тренировка под музыку',
    type: 'Кардио',
    level: 'Все уровни',
    trainerId: 'trainer_001',
    trainerName: 'Мария Иванова',
    maxParticipants: 25,
    currentParticipants: 20,
    startTime: DateTime(2025, 9, 22, 19, 0),
    endTime: DateTime(2025, 9, 22, 20, 0),
    location: 'Зал 1',
    price: 550,
  ),

  // Занятия на 23 сентября
  GroupClass(
    id: 'class_015',
    name: 'Тай-чи',
    description: 'Древняя китайская практика для гармонии тела и разума',
    type: 'Тай-чи',
    level: 'Начинающий',
    trainerId: 'trainer_003',
    trainerName: 'Елена Сидорова',
    maxParticipants: 20,
    currentParticipants: 12,
    startTime: DateTime(2025, 9, 23, 9, 30),
    endTime: DateTime(2025, 9, 23, 10, 30),
    location: 'Зал 2',
    price: 500,
  ),
  GroupClass(
    id: 'class_016',
    name: 'Бокс для начинающих',
    description: 'Основы бокса и самообороны',
    type: 'Бокс',
    level: 'Начинающий',
    trainerId: 'trainer_002',
    trainerName: 'Дмитрий Петров',
    maxParticipants: 15,
    currentParticipants: 8,
    startTime: DateTime(2025, 9, 23, 18, 0),
    endTime: DateTime(2025, 9, 23, 19, 0),
    location: 'Боксерский зал',
    price: 750,
  ),

  // Занятия на 24 сентября
  GroupClass(
    id: 'class_017',
    name: 'Аквааэробика',
    description: 'Тренировка в воде для снижения нагрузки на суставы',
    type: 'Аква',
    level: 'Все уровни',
    trainerId: 'trainer_001',
    trainerName: 'Мария Иванова',
    maxParticipants: 12,
    currentParticipants: 10,
    startTime: DateTime(2025, 9, 24, 10, 0),
    endTime: DateTime(2025, 9, 24, 11, 0),
    location: 'Бассейн',
    price: 850,
  ),
  GroupClass(
    id: 'class_018',
    name: 'Йога нидра',
    description: 'Психический сон для глубокого расслабления',
    type: 'Йога',
    level: 'Все уровни',
    trainerId: 'trainer_003',
    trainerName: 'Елена Сидорова',
    maxParticipants: 18,
    currentParticipants: 14,
    startTime: DateTime(2025, 9, 24, 20, 0),
    endTime: DateTime(2025, 9, 24, 21, 0),
    location: 'Зал 2',
    price: 500,
  ),

  // Занятия на 25 сентября
  GroupClass(
    id: 'class_019',
    name: 'Функциональный тренинг утренний',
    description: 'Утренняя функциональная тренировка для бодрости',
    type: 'Функциональный',
    level: 'Средний',
    trainerId: 'trainer_002',
    trainerName: 'Дмитрий Петров',
    maxParticipants: 18,
    currentParticipants: 12,
    startTime: DateTime(2025, 9, 25, 8, 0),
    endTime: DateTime(2025, 9, 25, 9, 0),
    location: 'Зал 1',
    price: 600,
  ),
  GroupClass(
    id: 'class_020',
    name: 'Теннисный турнир',
    description: 'Еженедельный турнир по теннису для всех желающих',
    type: 'Теннис',
    level: 'Все уровни',
    trainerId: 'trainer_001',
    trainerName: 'Мария Иванова',
    maxParticipants: 16,
    currentParticipants: 14,
    startTime: DateTime(2025, 9, 25, 15, 0),
    endTime: DateTime(2025, 9, 25, 17, 0),
    location: 'Корт 1-2',
    price: 1000,
  ),
];