import '../../models/trainer_model.dart';

final List<GroupClass> groupClasses = [
  // Занятия на сегодня (17 сентября)
  GroupClass(
    id: 'class_001',
    name: 'Утренняя йога',
    description: 'Расслабляющая утренняя практика для пробуждения тела и разума',
    type: 'Йога',
    level: 'Начинающий',
    trainerId: 'trainer_003',
    trainerName: 'Елена Сидорова',
    maxParticipants: 15,
    currentParticipants: 12,
    startTime: DateTime(2025, 9, 17, 8, 0),
    endTime: DateTime(2025, 9, 17, 9, 0),
    location: 'Зал 2',
    price: 500,
  ),
  GroupClass(
    id: 'class_002',
    name: 'HIIT тренировка',
    description: 'Высокоинтенсивная интервальная тренировка для сжигания жира',
    type: 'Кардио',
    level: 'Продвинутый',
    trainerId: 'trainer_001',
    trainerName: 'Мария Иванова',
    maxParticipants: 20,
    currentParticipants: 18,
    startTime: DateTime(2025, 9, 17, 18, 0),
    endTime: DateTime(2025, 9, 17, 19, 0),
    location: 'Зал 1',
    price: 600,
  ),
  GroupClass(
    id: 'class_003',
    name: 'Массаж расслабляющий',
    description: 'Расслабляющий массаж всего тела для снятия напряжения',
    type: 'Массаж',
    level: 'Все уровни',
    trainerId: 'trainer_massage',
    trainerName: 'Анна Ковалева',
    maxParticipants: 1,
    currentParticipants: 0,
    startTime: DateTime(2025, 9, 17, 19, 30),
    endTime: DateTime(2025, 9, 17, 20, 30),
    location: 'Массажный кабинет',
    price: 2500,
  ),

  // Занятия на завтра (18 сентября)
  GroupClass(
    id: 'class_004',
    name: 'Теннисный корт - утренняя сессия',
    description: 'Аренда теннисного корта для индивидуальной тренировки',
    type: 'Теннис',
    level: 'Все уровни',
    trainerId: '',
    trainerName: 'Самостоятельно',
    maxParticipants: 4,
    currentParticipants: 1,
    startTime: DateTime(2025, 9, 18, 9, 0),
    endTime: DateTime(2025, 9, 18, 10, 0),
    location: 'Корт 2',
    price: 1200,
  ),
  GroupClass(
    id: 'class_005',
    name: 'Пилатес',
    description: 'Укрепление мышечного корсета и улучшение осанки',
    type: 'Пилатес',
    level: 'Средний',
    trainerId: 'trainer_003',
    trainerName: 'Елена Сидорова',
    maxParticipants: 12,
    currentParticipants: 8,
    startTime: DateTime(2025, 9, 18, 17, 0),
    endTime: DateTime(2025, 9, 18, 18, 0),
    location: 'Зал 3',
    price: 550,
  ),

  // Занятия на послезавтра (19 сентября)
  GroupClass(
    id: 'class_006',
    name: 'Теннис с тренером',
    description: 'Индивидуальное занятие по тенnis с профессиональным тренером',
    type: 'Тенnis',
    level: 'Продвинутый',
    trainerId: 'trainer_001',
    trainerName: 'Мария Иванова',
    maxParticipants: 1,
    currentParticipants: 1,
    startTime: DateTime(2025, 9, 19, 16, 0),
    endTime: DateTime(2025, 9, 19, 17, 0),
    location: 'Корт 1',
    price: 2000,
  ),
  GroupClass(
    id: 'class_007',
    name: 'Функциональный тренинг',
    description: 'Тренировка для развития силы, выносливости и координации',
    type: 'Функциональный',
    level: 'Средний',
    trainerId: 'trainer_002',
    trainerName: 'Дмитрий Петров',
    maxParticipants: 15,
    currentParticipants: 10,
    startTime: DateTime(2025, 9, 19, 19, 0),
    endTime: DateTime(2025, 9, 19, 20, 0),
    location: 'Зал 1',
    price: 650,
  ),
];