import '../../models/payment_model.dart';

final List<MembershipType> membershipTypes = [
  MembershipType(
    id: 'type_001',
    name: 'Тренажерный зал (Базовый)',
    description: 'Доступ только в тренажерный зал в дневное время',
    price: 5000,
    durationDays: 30,
    maxVisits: 8,
    includesGym: true,
  ),
  MembershipType(
    id: 'type_002',
    name: 'Тренажерный зал (Полный)',
    description: 'Полный доступ в тренажерный зал без ограничений',
    price: 8000,
    durationDays: 30,
    maxVisits: 12,
    includesGym: true,
  ),
  MembershipType(
    id: 'type_003',
    name: 'Групповые занятия (Базовый)',
    description: 'Доступ к 8 групповым занятиям в месяц',
    price: 9000,
    durationDays: 30,
    maxVisits: 8,
    includesGroupClasses: true,
  ),
  MembershipType(
    id: 'type_004',
    name: 'Групповые занятия (Неограниченный)',
    description: 'Неограниченный доступ ко всем групповым занятиям',
    price: 12000,
    durationDays: 30,
    includesGroupClasses: true,
  ),
  MembershipType(
    id: 'type_005',
    name: 'Теннис (Начинающий)',
    description: 'Доступ к теннисным кортам + 4 часа в месяц',
    price: 12000,
    durationDays: 30,
    includesTennis: true,
    maxVisits: 4,
    tennisCourtDiscount: 0.1,
  ),
  MembershipType(
    id: 'type_006',
    name: 'Теннис (Профессионал)',
    description: 'Доступ к теннисным кортам + 8 часов в месяц',
    price: 18000,
    durationDays: 30,
    includesTennis: true,
    maxVisits: 8,
    tennisCourtDiscount: 0.15,
  ),
  MembershipType(
    id: 'type_007',
    name: 'All-inclusive (Стандарт)',
    description: 'Полный доступ ко всем услугам клуба',
    price: 25000,
    durationDays: 30,
    includesTennis: true,
    includesGym: true,
    includesGroupClasses: true,
    tennisCourtDiscount: 0.2,
    personalTrainingDiscount: 0.15,
  ),
  MembershipType(
    id: 'type_008',
    name: 'All-inclusive (Премиум)',
    description: 'Премиальный доступ со всеми привилегиями',
    price: 35000,
    durationDays: 30,
    includesTennis: true,
    includesGym: true,
    includesGroupClasses: true,
    tennisCourtDiscount: 0.3,
    personalTrainingDiscount: 0.2,
  ),
  MembershipType(
    id: 'type_009',
    name: 'Семейный пакет',
    description: 'Для двух взрослых и одного ребенка',
    price: 45000,
    durationDays: 30,
    includesTennis: true,
    includesGym: true,
    includesGroupClasses: true,
    tennisCourtDiscount: 0.25,
    personalTrainingDiscount: 0.15,
  ),
  MembershipType(
    id: 'type_010',
    name: 'Студенческий',
    description: 'Специальное предложение для студентов',
    price: 6000,
    durationDays: 30,
    maxVisits: 10,
    includesGym: true,
    includesGroupClasses: true,
  ),
  MembershipType(
    id: 'type_011',
    name: 'Корпоративный',
    description: 'Специальные условия для сотрудников компаний-партнеров',
    price: 20000,
    durationDays: 30,
    includesTennis: true,
    includesGym: true,
    includesGroupClasses: true,
    tennisCourtDiscount: 0.25,
  ),
  MembershipType(
    id: 'type_012',
    name: 'Годовой абонемент (Эконом)',
    description: 'Годовой доступ с экономией 15%',
    price: 85000,
    durationDays: 365,
    includesGym: true,
    includesGroupClasses: true,
  ),
  MembershipType(
    id: 'type_013',
    name: 'Годовой абонемент (Премиум)',
    description: 'Годовой премиальный доступ с экономией 20%',
    price: 280000,
    durationDays: 365,
    includesTennis: true,
    includesGym: true,
    includesGroupClasses: true,
    tennisCourtDiscount: 0.25,
    personalTrainingDiscount: 0.2,
  ),
  MembershipType(
    id: 'type_014',
    name: 'Пробный недельный',
    description: 'Пробный доступ на 7 дней ко всем услугам',
    price: 3000,
    durationDays: 7,
    includesTennis: true,
    includesGym: true,
    includesGroupClasses: true,
  ),
];