import 'package:flutter/material.dart';
import '../../models/news_banner_model.dart';

class NewsBannerData {
  static final List<NewsBanner> banners = [
    NewsBanner(
      id: '1',
      title: '🔥 ГОРЯЧАЯ РАСПРОДАЖА: СКИДКА 50%!',
      description: 'Только до конца недели! Все абонементы и услуги со скидкой 50%. Успей забронировать!',
      backgroundColor: const Color(0xFFFF6B35),
      textColor: Colors.white,
      actionText: 'Купить со скидкой',
      actionRoute: 'membership',
    ),
    NewsBanner(
      id: '2',
      title: '🎾 ТЕННИСНЫЙ СЕЗОН: СКИДКА 40%',
      description: 'Открытие теннисного сезона! Бронируйте корты на весь сезон со скидкой 40%.',
      backgroundColor: const Color(0xFF0066CC),
      textColor: Colors.white,
      actionText: 'Забронировать корт',
      actionRoute: 'tennis',
    ),
    NewsBanner(
      id: '3',
      title: '💪 ПРЕМИУМ АБОНЕМЕНТ: СКИДКА 35%',
      description: 'Полный доступ ко всем зонам клуба. Только для новых клиентов - скидка 35%!',
      backgroundColor: const Color(0xFF4CAF50),
      textColor: Colors.white,
      actionText: 'Приобрести',
      actionRoute: 'membership',
    ),
    NewsBanner(
      id: '4',
      title: '👥 ПРИВЕДИ ДРУГА - ПОЛУЧИ 20%',
      description: 'Приведи друга в клуб и получи скидку 20% на следующий месяц!',
      backgroundColor: const Color(0xFF9C27B0),
      textColor: Colors.white,
      actionText: 'Узнать условия',
      actionRoute: 'membership',
    ),
    NewsBanner(
      id: '5',
      title: '🏋️‍♂️ ПЕРСОНАЛЬНЫЙ ТРЕНЕР: СКИДКА 30%',
      description: 'Персональные тренировки с топ-тренерами. Первые 5 занятий со скидкой 30%!',
      backgroundColor: const Color(0xFFF44336),
      textColor: Colors.white,
      actionText: 'Выбрать тренера',
      actionRoute: 'trainers',
    ),
    NewsBanner(
      id: '6',
      title: '🎯 ЧЕРНАЯ ПЯТНИЦА: СКИДКИ ДО 60%',
      description: 'Самые большие скидки года! Только в эту пятницу - скидки до 60% на все услуги!',
      backgroundColor: const Color(0xFF333333),
      textColor: Colors.white,
      actionText: 'Посмотреть акции',
      actionRoute: 'membership',
    ),
    NewsBanner(
      id: '7',
      title: '🏊 БАССЕЙН + САУНА: СКИДКА 25%',
      description: 'Комплексный абонемент "Бассейн + Сауна". Специальная цена - скидка 25%!',
      backgroundColor: const Color(0xFF2196F3),
      textColor: Colors.white,
      actionText: 'Купить пакет',
      actionRoute: 'membership',
    ),
    NewsBanner(
      id: '8',
      title: '⭐ НОВЫЙ ГОД: СКИДКА 40%',
      description: 'Встречайте Новый год в форме! Годовые абонементы со скидкой 40%.',
      backgroundColor: const Color(0xFFFF9800),
      textColor: Colors.white,
      actionText: 'Забронировать',
      actionRoute: 'membership',
    ),
    NewsBanner(
      id: '9',
      title: '👨‍👩‍👧‍👦 СЕМЕЙНЫЙ АБОНЕМЕНТ: СКИДКА 45%',
      description: 'Специальное предложение для семей! Абонемент для всей семьи со скидкой 45%.',
      backgroundColor: const Color(0xFFE91E63),
      textColor: Colors.white,
      actionText: 'Купить семейный',
      actionRoute: 'membership',
    ),
    NewsBanner(
      id: '10',
      title: '🎁 БОНУС: 3 МЕСЯЦА В ПОДАРОК',
      description: 'При покупке годового абонемента - 3 месяца в подарок! Ограниченное предложение.',
      backgroundColor: const Color(0xFF795548),
      textColor: Colors.white,
      actionText: 'Получить подарок',
      actionRoute: 'membership',
    ),
    NewsBanner(
      id: '11',
      title: '💳 РАССРОЧКА 0% НА 12 МЕСЯЦЕВ',
      description: 'Оформите абонемент в рассрочку без процентов на 12 месяцев!',
      backgroundColor: const Color(0xFF607D8B),
      textColor: Colors.white,
      actionText: 'Оформить рассрочку',
      actionRoute: 'membership',
    ),
    NewsBanner(
      id: '12',
      title: '🏆 КОРПОРАТИВНЫЕ СКИДКИ: ДО 50%',
      description: 'Специальные условия для компаний. Скидки до 50% для сотрудников!',
      backgroundColor: const Color(0xFF3F51B5),
      textColor: Colors.white,
      actionText: 'Узнать условия',
      actionRoute: 'membership',
    ),
    NewsBanner(
      id: '13',
      title: '🎯 РАННЕЕ БРОНИРОВАНИЕ: СКИДКА 30%',
      description: 'Забронируйте услуги на следующий месяц и получите скидку 30%!',
      backgroundColor: const Color(0xFF009688),
      textColor: Colors.white,
      actionText: 'Забронировать заранее',
      actionRoute: 'schedule',
    ),
    NewsBanner(
      id: '14',
      title: '🔥 ЛЕТНЯЯ РАСПРОДАЖА: СКИДКА 35%',
      description: 'Летние скидки на все виды тренировок! Готовься к лету с выгодой!',
      backgroundColor: const Color(0xFFFF5722),
      textColor: Colors.white,
      actionText: 'Начать тренировки',
      actionRoute: 'class_selection',
    ),
    NewsBanner(
      id: '15',
      title: '⭐ VIP КАРТА: ПЕРСОНАЛЬНЫЕ СКИДКИ',
      description: 'Станьте VIP-клиентом и получайте персональные скидки до 40% круглый год!',
      backgroundColor: const Color(0xFFFFC107),
      textColor: Colors.black,
      actionText: 'Стать VIP',
      actionRoute: 'membership',
    ),
  ];
}