import '../../models/trainer_model.dart';

final List<Trainer> trainers = [
  Trainer(
    id: 'trainer_001',
    firstName: 'Мария',
    lastName: 'Иванова',
    specialty: 'Теннис, Кардио-тренировки',
    bio: 'Профессиональный тренер с 10-летним опытом. Специализация: теннис для начинающих и продвинутых игроков, кардио-тренировки. Чемпионка региона по теннису.',
    rating: 4.8,
    totalReviews: 124,
    certifications: ['ITF Level 2', 'Fitness Instructor Certification', 'Tennis Coach Professional'],
    photoUrl: null,
    availableSports: ['теннис', 'кардио', 'функциональный тренинг', 'кроссфит'],
    hourlyRates: {'теннис': 2000, 'персональная тренировка': 1500, 'групповое занятие': 800},
  ),
  Trainer(
    id: 'trainer_002',
    firstName: 'Дмитрий',
    lastName: 'Петров',
    specialty: 'Силовые тренировки, Бодибилдинг',
    bio: 'Мастер спорта по пауэрлифтингу. Специализируется на силовых тренировках и построении мышечной массы. Опыт работы - 8 лет.',
    rating: 4.9,
    totalReviews: 89,
    certifications: ['Master Trainer', 'Nutrition Specialist', 'Strength & Conditioning Coach'],
    photoUrl: null,
    availableSports: ['силовые тренировки', 'бодибилдинг', 'кроссфит', 'пауэрлифтинг'],
    hourlyRates: {'персональная тренировка': 1800, 'консультация по питанию': 1200},
  ),
  Trainer(
    id: 'trainer_003',
    firstName: 'Елена',
    lastName: 'Сидорова',
    specialty: 'Йога, Пилатес, Стретчинг',
    bio: 'Сертифицированный инструктор по йоге и пилатесу с 12-летним опытом. Помогает достичь гармонии тела и разума. Проводит ретриты и мастер-классы.',
    rating: 4.7,
    totalReviews: 67,
    certifications: ['Yoga Alliance 500h', 'Pilates Instructor', 'Yoga Therapy', 'Meditation Teacher'],
    photoUrl: null,
    availableSports: ['йога', 'пилатес', 'стретчинг', 'медитация', 'тай-чи'],
    hourlyRates: {'групповое занятие': 800, 'персональное': 1200, 'медитация': 600},
  ),
  Trainer(
    id: 'trainer_004',
    firstName: 'Анна',
    lastName: 'Ковалева',
    specialty: 'Массаж, Реабилитация',
    bio: 'Сертифицированный массажист с медицинским образованием. Специализируется на спортивном массаже, реабилитации после травм и расслабляющих процедурах.',
    rating: 4.9,
    totalReviews: 156,
    certifications: ['Medical Massage Therapist', 'Sports Rehabilitation', 'Thai Massage'],
    photoUrl: null,
    availableSports: ['массаж', 'реабилитация', 'стретчинг'],
    hourlyRates: {'спортивный массаж': 2500, 'релаксационный массаж': 2000, 'реабилитация': 1800},
  ),
  Trainer(
    id: 'trainer_005',
    firstName: 'Алексей',
    lastName: 'Смирнов',
    specialty: 'Бокс, MMA, Самооборона',
    bio: 'Профессиональный тренер по боксу и MMA. Чемпион города по боксу. Обучает как начинающих, так и продвинутых спортсменов.',
    rating: 4.8,
    totalReviews: 92,
    certifications: ['Boxing Coach', 'MMA Trainer', 'Self-Defense Instructor'],
    photoUrl: null,
    availableSports: ['бокс', 'mma', 'самооборона', 'кикбоксинг'],
    hourlyRates: {'бокс': 1700, 'mma': 1900, 'групповое занятие': 700},
  ),
  Trainer(
    id: 'trainer_006',
    firstName: 'Ольга',
    lastName: 'Новикова',
    specialty: 'Танцы, Zumba, Cardio Dance',
    bio: 'Профессиональная танцовщица и инструктор групповых программ. Создает энергичную и позитивную атмосферу на занятиях.',
    rating: 4.6,
    totalReviews: 78,
    certifications: ['Zumba Instructor', 'Dance Fitness', 'Aerobics Instructor'],
    photoUrl: null,
    availableSports: ['танцы', 'zumba', 'кардио-танцы', 'аэробика'],
    hourlyRates: {'групповое занятие': 600, 'персональное': 1000, 'хореография': 1500},
  ),
  Trainer(
    id: 'trainer_007',
    firstName: 'Иван',
    lastName: 'Кузнецов',
    specialty: 'Плавание, Триатлон',
    bio: 'Мастер спорта по плаванию. Тренер по плаванию для взрослых и детей. Готовит к соревнованиям и триатлону.',
    rating: 4.7,
    totalReviews: 63,
    certifications: ['Swimming Coach', 'Triathlon Trainer', 'Water Safety Instructor'],
    photoUrl: null,
    availableSports: ['плавание', 'триатлон', 'аквааэробика'],
    hourlyRates: {'персональная тренировка': 1600, 'групповое занятие': 500, 'консультация': 800},
  ),
  Trainer(
    id: 'trainer_008',
    firstName: 'Светлана',
    lastName: 'Попова',
    specialty: 'Функциональный тренинг, TRX',
    bio: 'Сертифицированный тренер по функциональному тренингу и TRX. Специализируется на развитии функциональной силы и выносливости.',
    rating: 4.8,
    totalReviews: 45,
    certifications: ['TRX Instructor', 'Functional Training', 'Kettlebell Coach'],
    photoUrl: null,
    availableSports: ['функциональный тренинг', 'trx', 'гиревой спорт', 'кроссфит'],
    hourlyRates: {'персональная тренировка': 1400, 'trx': 1200, 'групповое занятие': 550},
  ),
  Trainer(
    id: 'trainer_009',
    firstName: 'Михаил',
    lastName: 'Васильев',
    specialty: 'Бег, Легкая атлетика',
    bio: 'Мастер спорта по легкой атлетике. Тренер по бегу для любителей и профессионалов. Составляет индивидуальные планы тренировок.',
    rating: 4.5,
    totalReviews: 38,
    certifications: ['Running Coach', 'Athletics Trainer', 'Marathon Preparation'],
    photoUrl: null,
    availableSports: ['бег', 'легкая атлетика', 'марафон', 'спортивная ходьба'],
    hourlyRates: {'персональная тренировка': 1300, 'составление плана': 900, 'групповое занятие': 400},
  ),
  Trainer(
    id: 'trainer_010',
    firstName: 'Наталья',
    lastName: 'Федорова',
    specialty: 'Пилатес, Йога для беременных',
    bio: 'Сертифицированный инструктор по пилатесу и йоге для беременных. Специализируется на работе с женщинами и подготовке к родам.',
    rating: 4.9,
    totalReviews: 112,
    certifications: ['Pilates for Women', 'Prenatal Yoga', 'Postnatal Recovery'],
    photoUrl: null,
    availableSports: ['пилатес', 'йога для беременных', 'послеродовое восстановление'],
    hourlyRates: {'персональное занятие': 1400, 'групповое занятие': 650, 'консультация': 800},
  ),
];